<?php

use App\User;
use Illuminate\Database\Seeder;

class ProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'userData' => [
                    'first_name' => 'Karan',
                    'last_name' => 'Batra',
                    'email' => 'karan@yopmail.com',
                    'alternate_email' => 'karan@yopmail.com',
                    'dob' => '19-04-1991',
                    'gender' => 'male',
                    'marital_status' => 'single',
                    'phone' => '1234567890',
                    'alternate_phone' => '1234567890',
                    'family_phone_number' => '1234567890',
                    'landline' => '1234567890',
                    'whatsup' => '1234567890',
                    'role_id' => 2,
                    'status' => 1,
                    'password' => bcrypt('password')
                ],
                'profileData' => [
                    'height' => 153,
                    'religion' => 'hindu',
                    'caste_id' => 1,
                    'sub_caste_id' => null,
                    'mother_tongue' => 'hindi',
                    'country' => 'india',
                    'state' => 'Uttarakhand',
                    'city' => 'Dehradun',
                    'annual_income' => 800000,
                    'profile_picture1' => null,
                    'profile_picture1' => null,
                    'weight' => 80,
                    'personal_detail' => 'Dummy Text',
                    'body_type' => null,
                    'complexion' => null,
                    'challanged' => null,
                    'education' => null,
                    'higher_education' => null,
                    'occupation' => null,
                    'birth_time' => null,
                    'mangalik_status' => null,
                    'non_veg' => 1,
                    'drink' => 1,
                    'smoke' => 1,
                    'own_house' => 1,
                    'own_car' => 1,
                    'gothra' => null,
                ]

            ],
            [
                'userData' => [
                    'first_name' => 'Udit',
                    'last_name' => 'Batra',
                    'email' => 'udit@yopmail.com',
                    'alternate_email' => 'karan@yopmail.com',
                    'dob' => '19-04-1991',
                    'gender' => 'male',
                    'marital_status' => 'single',
                    'phone' => '1234567890',
                    'alternate_phone' => '1234567890',
                    'family_phone_number' => '1234567890',
                    'landline' => '1234567890',
                    'whatsup' => '1234567890',
                    'role_id' => 2,
                    'status' => 1,
                    'password' => bcrypt('password')
                ],
                'profileData' => [
                    'height' => 153,
                    'religion' => 'hindu',
                    'caste_id' => 5,
                    'sub_caste_id' => null,
                    'mother_tongue' => 'hindi',
                    'country' => 'india',
                    'state' => 'Uttarakhand',
                    'city' => 'Dehradun',
                    'annual_income' => 800000,
                    'profile_picture1' => null,
                    'profile_picture1' => null,
                    'weight' => 80,
                    'personal_detail' => 'Dummy Text',
                    'body_type' => null,
                    'complexion' => null,
                    'challanged' => null,
                    'education' => null,
                    'higher_education' => null,
                    'occupation' => null,
                    'birth_time' => null,
                    'mangalik_status' => null,
                    'non_veg' => 1,
                    'drink' => 1,
                    'smoke' => 1,
                    'own_house' => 1,
                    'own_car' => 1,
                    'gothra' => null,
                ]

            ],
            [
                'userData' => [
                    'first_name' => 'Rahul',
                    'last_name' => 'Joshi',
                    'email' => 'rahul@yopmail.com',
                    'alternate_email' => 'rahul@yopmail.com',
                    'dob' => '01-03-1989',
                    'gender' => 'male',
                    'marital_status' => 'single',
                    'phone' => '1234567890',
                    'alternate_phone' => '1234567890',
                    'family_phone_number' => '1234567890',
                    'landline' => '1234567890',
                    'whatsup' => '1234567890',
                    'role_id' => 2,
                    'status' => 1,
                    'password' => bcrypt('password')
                ],
                'profileData' => [
                    'height' => 153,
                    'religion' => 'hindu',
                    'caste_id' => 4,
                    'sub_caste_id' => null,
                    'mother_tongue' => 'hindi',
                    'country' => 'india',
                    'state' => 'Uttarakhand',
                    'city' => 'Dehradun',
                    'annual_income' => 800000,
                    'profile_picture1' => null,
                    'profile_picture1' => null,
                    'weight' => 80,
                    'personal_detail' => 'Dummy Text',
                    'body_type' => null,
                    'complexion' => null,
                    'challanged' => null,
                    'education' => null,
                    'higher_education' => null,
                    'occupation' => null,
                    'birth_time' => null,
                    'mangalik_status' => null,
                    'non_veg' => 1,
                    'drink' => 1,
                    'smoke' => 1,
                    'own_house' => 1,
                    'own_car' => 1,
                    'gothra' => null,
                ]

            ],
            [
                'userData' => [
                    'first_name' => 'Aakash',
                    'last_name' => 'Gupta',
                    'email' => 'aakash@yopmail.com',
                    'alternate_email' => 'aakash@yopmail.com',
                    'dob' => '19-04-1991',
                    'gender' => 'male',
                    'marital_status' => 'single',
                    'phone' => '1234567890',
                    'alternate_phone' => '1234567890',
                    'family_phone_number' => '1234567890',
                    'landline' => '1234567890',
                    'whatsup' => '1234567890',
                    'role_id' => 2,
                    'status' => 1,
                    'password' => bcrypt('password')
                ],
                'profileData' => [
                    'height' => 153,
                    'religion' => 'hindu',
                    'caste_id' => 3,
                    'sub_caste_id' => null,
                    'mother_tongue' => 'hindi',
                    'country' => 'india',
                    'state' => 'Uttarakhand',
                    'city' => 'Dehradun',
                    'annual_income' => 800000,
                    'profile_picture1' => null,
                    'profile_picture1' => null,
                    'weight' => 80,
                    'personal_detail' => 'Dummy Text',
                    'body_type' => null,
                    'complexion' => null,
                    'challanged' => null,
                    'education' => null,
                    'higher_education' => null,
                    'occupation' => null,
                    'birth_time' => null,
                    'mangalik_status' => null,
                    'non_veg' => 1,
                    'drink' => 1,
                    'smoke' => 1,
                    'own_house' => 1,
                    'own_car' => 1,
                    'gothra' => null,
                ]

            ], [
                'userData' => [
                    'first_name' => 'Deepika',
                    'last_name' => 'Padukone',
                    'email' => 'deepika@yopmail.com',
                    'alternate_email' => 'deepika@yopmail.com',
                    'dob' => '11-04-1993',
                    'gender' => 'female',
                    'marital_status' => 'single',
                    'phone' => '1234567890',
                    'alternate_phone' => '1234567890',
                    'family_phone_number' => '1234567890',
                    'landline' => '1234567890',
                    'whatsup' => '1234567890',
                    'role_id' => 2,
                    'status' => 1,
                    'password' => bcrypt('password')
                ],
                'profileData' => [
                    'height' => 153,
                    'religion' => 'hindu',
                    'caste_id' => 2,
                    'sub_caste_id' => null,
                    'mother_tongue' => 'hindi',
                    'country' => 'india',
                    'state' => 'Uttarakhand',
                    'city' => 'Dehradun',
                    'annual_income' => 800000,
                    'profile_picture1' => null,
                    'weight' => 80,
                    'personal_detail' => 'Dummy Text',
                    'body_type' => null,
                    'complexion' => null,
                    'challanged' => null,
                    'education' => null,
                    'higher_education' => null,
                    'occupation' => null,
                    'birth_time' => null,
                    'mangalik_status' => null,
                    'non_veg' => 1,
                    'drink' => 1,
                    'smoke' => 1,
                    'own_house' => 1,
                    'own_car' => 1,
                    'gothra' => null,
                ]

            ], [
                'userData' => [
                    'first_name' => 'Riya',
                    'last_name' => 'Chakroborty',
                    'email' => 'riya@yopmail.com',
                    'alternate_email' => 'riya@yopmail.com',
                    'dob' => '12-02-1990',
                    'gender' => 'female',
                    'marital_status' => 'single',
                    'phone' => '1234567890',
                    'alternate_phone' => '1234567890',
                    'family_phone_number' => '1234567890',
                    'landline' => '1234567890',
                    'whatsup' => '1234567890',
                    'role_id' => 2,
                    'status' => 1,
                    'password' => bcrypt('password')
                ],
                'profileData' => [
                    'height' => 153,
                    'religion' => 'hindu',
                    'caste_id' => 1,
                    'sub_caste_id' => null,
                    'mother_tongue' => 'hindi',
                    'country' => 'india',
                    'state' => 'Uttarakhand',
                    'city' => 'Dehradun',
                    'annual_income' => 800000,
                    'profile_picture1' => null,
                    'profile_picture1' => null,
                    'weight' => 80,
                    'personal_detail' => 'Dummy Text',
                    'body_type' => null,
                    'complexion' => null,
                    'challanged' => null,
                    'education' => null,
                    'higher_education' => null,
                    'occupation' => null,
                    'birth_time' => null,
                    'mangalik_status' => null,
                    'non_veg' => 1,
                    'drink' => 1,
                    'smoke' => 1,
                    'own_house' => 1,
                    'own_car' => 1,
                    'gothra' => null,
                ]

            ], [
                'userData' => [
                    'first_name' => 'suhana',
                    'last_name' => 'Sharma',
                    'email' => 'suhana@yopmail.com',
                    'alternate_email' => 'suhana@yopmail.com',
                    'dob' => '19-04-1987',
                    'gender' => 'female',
                    'marital_status' => 'single',
                    'phone' => '1234567890',
                    'alternate_phone' => '1234567890',
                    'family_phone_number' => '1234567890',
                    'landline' => '1234567890',
                    'whatsup' => '1234567890',
                    'role_id' => 2,
                    'status' => 1,
                    'password' => bcrypt('password')
                ],
                'profileData' => [
                    'height' => 153,
                    'religion' => 'hindu',
                    'caste_id' => 3,
                    'sub_caste_id' => null,
                    'mother_tongue' => 'hindi',
                    'country' => 'india',
                    'state' => 'Uttarakhand',
                    'city' => 'Dehradun',
                    'annual_income' => 800000,
                    'profile_picture1' => null,
                    'profile_picture1' => null,
                    'weight' => 80,
                    'personal_detail' => 'Dummy Text',
                    'body_type' => null,
                    'complexion' => null,
                    'challanged' => null,
                    'education' => null,
                    'higher_education' => null,
                    'occupation' => null,
                    'birth_time' => null,
                    'mangalik_status' => null,
                    'non_veg' => 1,
                    'drink' => 1,
                    'smoke' => 1,
                    'own_house' => 1,
                    'own_car' => 1,
                    'gothra' => null,
                ]

            ], [
                'userData' => [
                    'first_name' => 'Subham',
                    'last_name' => 'Aggarwal',
                    'email' => 'subham@yopmail.com',
                    'alternate_email' => 'subham@yopmail.com',
                    'dob' => '05-08-1986',
                    'gender' => 'male',
                    'marital_status' => 'single',
                    'phone' => '1234567890',
                    'alternate_phone' => '1234567890',
                    'family_phone_number' => '1234567890',
                    'landline' => '1234567890',
                    'whatsup' => '1234567890',
                    'role_id' => 2,
                    'status' => 1,
                    'password' => bcrypt('password')
                ],
                'profileData' => [
                    'height' => 153,
                    'religion' => 'hindu',
                    'caste_id' => 2,
                    'sub_caste_id' => null,
                    'mother_tongue' => 'hindi',
                    'country' => 'india',
                    'state' => 'Uttarakhand',
                    'city' => 'Dehradun',
                    'annual_income' => 800000,
                    'profile_picture1' => null,
                    'profile_picture1' => null,
                    'weight' => 80,
                    'personal_detail'=> 'Dummy Text',
                    'body_type' => null,
                    'complexion' => null,
                    'challanged' => null,
                    'education' => null,
                    'higher_education' => null,
                    'occupation' => null,
                    'birth_time' => null,
                    'mangalik_status' => null,
                    'non_veg' => 1,
                    'drink' => 1,
                    'smoke' => 1,
                    'own_house' => 1,
                    'own_car' => 1,
                    'gothra' => null,
                ]

            ]
        ];

        foreach ($data as $value) {
            $value['userData']['dob'] = date('Y-m-d', strtotime($value['userData']['dob']));
            $from = new DateTime($value['userData']['dob']);
            $to = new DateTime('today');
            $age = $from->diff($to)->y;
            $value['userData']['age'] = $age;
            $user = User::create($value['userData']);


            $user->userProfile()->create($value['profileData']);
        }

    }
}
